version: "3.9"
services:
  gitlab:
    image: gitlab/gitlab-ee:latest
    ports:
      - 80:80
      - 443:443
      - 22:22
    volumes:
      - ./gitlab/config:/etc/gitlab
      - gitlab_logs:/var/log/gitlab
      - gitlab_data:/var/opt/gitlab
    shm_size: '256m'
    
volumes:
  gitlab_logs:
  gitlab_data:

